ARG CONTRIBUTIONS_API_URL=https://contributions.api.dev.josa.ngo HOST=0.0.0.0 PORT=3000 USER=node MATOMO_SITE_ID=11 TARGET_ENV CI_REPO  CI_REPO_NAME  CI_REPO_URL  CI_COMMIT_SHA  CI_COMMIT_REF  CI_PIPELINE_URL  CI_PIPELINE_CREATED  CI_PREV_PIPELINE_URL  CI_PIPELINE_NUMBER DEBUG='false'

###########
# BUILDER #
###########
FROM node:16-alpine3.14 as builder

ARG CONTRIBUTIONS_API_URL
ARG HOST
ARG PORT
ARG MATOMO_SITE_ID
ARG TARGET_ENV
ARG CI_REPO
ARG CI_REPO_NAME
ARG CI_REPO_URL
ARG CI_COMMIT_SHA
ARG CI_COMMIT_REF
ARG CI_PIPELINE_URL
ARG CI_PIPELINE_CREATED
ARG CI_PIPELINE_NUMBER
ARG DEBUG

# copy build context and install dependencies
WORKDIR /workspace
COPY . .
RUN npm install

# Inject the enviromental variables
ENV CONTRIBUTIONS_API_URL=$CONTRIBUTIONS_API_URL HOST=$HOST PORT=$PORT MATOMO_SITE_ID=$MATOMO_SITE_ID TARGET_ENV=${TARGET_ENV} NUXT_PUBLIC_CI_BUILD_NUMBER=${CI_PIPELINE_NUMBER}  NUXT_PUBLIC_CI_BUILD_LINK=${CI_PIPELINE_URL} NUXT_PUBLIC_BUILD_REPO_LINK=${CI_REPO_URL} NUXT_PUBLIC_CI_COMMIT_SHA=${CI_COMMIT_SHA} NUXT_PUBLIC_CI_COMMIT_LINK=${CI_COMMIT_REF} NUXT_PUBLIC_BUILD_TIMESTAMP=${CI_PIPELINE_CREATED} DEBUG=${DEBUG}

# build NuxtJS project
RUN npm run build:modern

###########
# PROJECT #
###########
FROM node:16-slim

ARG CONTRIBUTIONS_API_URL
ARG HOST
ARG PORT
ARG USER
ARG MATOMO_SITE_ID
ARG TARGET_ENV
ARG CI_REPO
ARG CI_REPO_NAME
ARG CI_REPO_URL
ARG CI_COMMIT_SHA
ARG CI_COMMIT_REF
ARG CI_PIPELINE_URL
ARG CI_PIPELINE_CREATED
ARG CI_PIPELINE_NUMBER
ARG DEBUG

# copy builder output to project workdir
WORKDIR /app
COPY --from=builder --chown=${USER}:${USER} /workspace/.nuxt /app/.nuxt
COPY --from=builder --chown=${USER}:${USER} /workspace/nuxt.config.js /app/nuxt.config.js
COPY --from=builder --chown=${USER}:${USER} /workspace/node_modules /app/node_modules
COPY --from=builder --chown=${USER}:${USER} /workspace/package.json /app/

# Inject the enviromental variables
ENV CONTRIBUTIONS_API_URL=$CONTRIBUTIONS_API_URL HOST=$HOST PORT=$PORT MATOMO_SITE_ID=$MATOMO_SITE_ID TARGET_ENV=${TARGET_ENV} NUXT_PUBLIC_CI_BUILD_NUMBER=${CI_PIPELINE_NUMBER}  NUXT_PUBLIC_CI_BUILD_LINK=${CI_PIPELINE_URL} NUXT_PUBLIC_BUILD_REPO_LINK=${CI_REPO_URL} NUXT_PUBLIC_CI_COMMIT_SHA=${CI_COMMIT_SHA} NUXT_PUBLIC_CI_COMMIT_LINK=${CI_COMMIT_REF} NUXT_PUBLIC_BUILD_TIMESTAMP=${CI_PIPELINE_CREATED} DEBUG=${DEBUG}

# set user context
USER ${USER}

# expose port
EXPOSE ${PORT}

# run for production
CMD [ "npm", "run", "start:modern"]
