when:
  - event: [push, manual]
    branch: [main]
  - event: [pull_request]
    # Only run when PR targets main branch
    evaluate: 'CI_COMMIT_TARGET_BRANCH == "main"'
    # Build the source branch (not main)
    branch:
      exclude: [main]

variables:
  - &docker_repo "josaorg/contributions-web"
  - &slack_channel "builds"
  # Success message template
  - &success_message >
    ✅ *SUCCESS* - Stable Build #{{ build.number }}

    📁 *Repository:* {{ repo.name }}
    🌿 *Branch:* {{ build.branch }}
    📝 *Commit:* {{ truncate build.commit 8 }}
    👤 *Author:* {{ build.author }}

    🔗 *Links:*
    • <{{ build.link }}|View Build>
  # Failure message template
  - &failure_message >
    ❌ *FAILED* - Stable Build #{{ build.number }}

    📁 *Repository:* {{ repo.name }}
    🌿 *Branch:* {{ build.branch }}
    📝 *Commit:* {{ truncate build.commit 8 }}
    👤 *Author:* {{ build.author }}

    🔗 *Links:*
    • <{{ build.link }}|View Build>

steps:
  - name: run-pre-commit-hooks
    image: josaorg/pre-commit-runner
    settings:
      args: "--all-files"
      skip: "end-of-file-fixer, yamllint"

  # Build stable image (main branch only)
  - name: build-stable-image
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: *docker_repo
      dockerfile: ./Dockerfile
      tags:
        - ${CI_COMMIT_SHA:-latest}
        - stable
      username:
        from_secret: DOCKER_HUB_USERNAME
      password:
        from_secret: DOCKER_HUB_PASSWORD
      build_args:
        CI_REPO: "${CI_REPO}"
        CI_REPO_NAME: "${CI_REPO_NAME}"
        CI_REPO_URL: "${CI_REPO_URL}"
        CI_COMMIT_SHA: "${CI_COMMIT_SHA}"
        CI_COMMIT_REF: "${CI_COMMIT_REF}"
        CI_PIPELINE_URL: "${CI_PIPELINE_URL}"
        CI_PIPELINE_CREATED: "${CI_PIPELINE_CREATED}"
        CI_PREV_PIPELINE_URL: "${CI_PREV_PIPELINE_URL}"
        CI_PIPELINE_NUMBER: "${CI_PIPELINE_NUMBER}"
        CONTRIBUTIONS_API_URL: http://contributions.api.svc.cluster.local:80
        MATOMO_SITE_ID: "11"
        TARGET_ENV: production
    depends_on:
      - run-pre-commit-hooks

  # Slack notification for stable build success
  - name: notify-slack-stable-success
    image: plugins/slack
    settings:
      webhook:
        from_secret: SLACK_WEBHOOK
      channel: *slack_channel
      template: *success_message
    when:
      - status: success
    depends_on:
      - run-pre-commit-hooks
      - build-stable-image

  # Slack notification for stable build failure
  - name: notify-slack-stable-failure
    image: plugins/slack
    settings:
      webhook:
        from_secret: SLACK_WEBHOOK
      channel: *slack_channel
      template: *failure_message
    when:
      - status: failure
    depends_on:
      - run-pre-commit-hooks
      - build-stable-image
